baseURL: https://apisarenco.github.io
languageCode: en-us
title: Alexandru Pisarenco
theme: "anubis"
publishdir: docs

paginate: 10
#disqusShortname: "yourdiscussshortname"
#googleAnalytics: "G-12345"
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 1
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 0

params:
  author: "Alexandru Pisarenco"
  email: alex@lundas.net # used for microformats
  avatar: "avatar.png" # used for microformats
  description: ""
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-without-switcher
  readMore: true
  disableSummary: true
  # utteranc.es support
  #utterancesRepo: ""  # mandatory
  #utterancesTheme: "" # optional
  #utterancesIssue: "" # optional
  #utterancesLabel: "" # optional
  # isso support
  #isso:
  #  enabled: true # mandatory
  #  data: "https://comments.example.com/" # mandatory
  #  jsLocation: "https://comments.example.com/js/embed.min.js" # mandatory
  #  css: true # optional
  #  lang: "de" # optional
  #  replyToSelf: true # mandatory
  #  requireAuthor: true # mandatory
  #  requireEmail: true # mandatory
  #  id: "thread-id" # optional
  #  avatar: true # optional
  #  avatar-bg: "#f0f0f0" # optional
  #webmentions:
  #  url: https://yourdomain.com/webemntions/receive
  #  login: hugo-theme-anubis
  #  pingback: true
  social:
  - id: github
    name: apisarenco
  - id: linkedin
    url: "https://www.linkedin.com/in/apisarenco"
    #icon: "linkedin"
  - id: twitter
    url: https://twitter.com/apisarenco
    #icon: twitter
  - id: stackoverflow
    url: https://stackoverflow.com/users/234661/alex
    #icon: stackoverflow
  - id: reddit
    url: https://www.reddit.com/u/apisarenco
    #icon: reddit

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
