baseURL: https://apisarenco.github.io
languageCode: en-us
title: Alexandru Pisarenco
whoami: Tech enthusiast, software professional and absolute data nerd
theme: "beautifulhugo"
publishdir: docs

params:
  homeTitle: "Home"
  subtitle: 
  mainSections:
    - post
    - posts
  logo: avatar.png
  favicon: favicon.ico
  dateFormat: "2006-01-02"
  pygmentsCodeFences: True
  pygmentsUseClasses: True
  socialShare: True

author:
  name: Alexandru Pisarenco
  website: alex.lundas.net
  #email = "youremail@domain.com"
  #facebook = "username"
  github: apisarenco
  twitter: apisarenco
  reddit: apisarenco
  linkedin: apisarenco
  stackoverflow: users/234661/alex

menu:
  main:
    - name: Archive
      url: posts
      weight: 1

    - name: About
      url: about
      weight: 3
